import type { MetadataRoute } from 'next'
import { CONTENT_DATES } from '../lib/content-dates'
import { STATIC_ROUTES, absoluteUrl } from '../lib/routes'

function priorityFor(path: string): number {
  if (path === '/') return 1
  if (path === '/plan') return 0.9
  if (path === '/destinations') return 0.8
  if (path.startsWith('/destinations/')) return 0.8
  if (path === '/blog') return 0.6
  if (path.startsWith('/blog/')) return 0.7
  return 0.5
}

export default function sitemap(): MetadataRoute.Sitemap {
  return STATIC_ROUTES.map((path) => {
    // Real per-page date from lib/content-dates.ts (generated by
    // scripts/generate-content-dates.mjs). Never `new Date()`: stamping every
    // URL with the build time makes all 65 lastmods identical and re-dates the
    // whole site on every deploy, which is why Google stopped trusting this
    // sitemap for crawl scheduling. A page whose content has not changed must
    // keep its old lastmod across deploys.
    const contentDate = CONTENT_DATES[path]

    return {
      url: absoluteUrl(path),
      // Omitted rather than faked when a route has no known date — <lastmod> is
      // optional, and an untrue one is worse than none.
      ...(contentDate ? { lastModified: contentDate } : {}),
      changeFrequency: path === '/' || path === '/plan' ? ('weekly' as const) : ('monthly' as const),
      priority: priorityFor(path),
    }
  })
}
