import type { MetadataRoute } from 'next'
import { CONTENT_DATES } from '../lib/content-dates'

const BASE_URL = 'https://www.fairwaypal.com'

const STATIC_PAGES = [
  '/',
  '/plan',
  '/about',
  '/status',
  '/affiliate-disclosure',
  '/destinations',
  '/destinations/scottsdale',
  '/destinations/myrtle-beach',
  '/destinations/bandon-dunes',
  '/destinations/pinehurst',
  '/destinations/scotland',
  '/destinations/ireland',
  '/destinations/pebble-beach',
  '/destinations/kiawah-island',
  '/destinations/florida-golf',
  '/destinations/algarve',
  '/blog',
  '/blog/golf-trip-with-non-golfers',
  '/blog/best-bachelor-party-golf-destinations',
  '/blog/golf-trip-budget',
  '/blog/what-to-do-on-golf-trip-non-golfer',
  '/blog/golf-trip-packing-list',
  '/blog/scottsdale-vs-myrtle-beach-golf-trip',
  '/blog/how-to-plan-a-golf-trip',
  '/blog/ireland-vs-scotland-golf-trip',
  '/blog/pebble-beach-golf-trip',
  '/blog/kiawah-island-golf-trip',
  '/blog/golf-trip-group-size',
  '/blog/golf-trip-weekend-schedule',
  '/blog/pinehurst-vs-kiawah-island-golf-trip',
  '/blog/bandon-dunes-vs-pebble-beach-golf-trip',
  '/blog/algarve-vs-scotland-golf-trip',
  '/blog/how-to-split-costs-golf-trip',
  '/blog/bandon-dunes-for-non-golfers',
  '/blog/pebble-beach-for-non-golfers',
  '/blog/algarve-for-non-golfers',
  '/blog/pinehurst-for-non-golfers',
  '/blog/scotland-for-non-golfers',
  '/blog/pinehurst-vs-pebble-beach-golf-trip',
  '/blog/golf-trip-tipping-guide',
  '/blog/best-golf-trip-apps',
  '/blog/kiawah-island-for-non-golfers',
  '/blog/scottsdale-for-non-golfers',
  '/blog/pinehurst-vs-bandon-dunes-golf-trip',
  '/blog/shipping-clubs-vs-flying-with-clubs',
  '/blog/why-your-group-keeps-cancelling-golf-trip',
  '/blog/myrtle-beach-for-non-golfers',
  '/blog/ireland-for-non-golfers',
  '/blog/florida-for-non-golfers',
  '/blog/myrtle-beach-vs-pinehurst-golf-trip',
  '/blog/myrtle-beach-vs-kiawah-island-golf-trip',
  '/blog/scottsdale-vs-pinehurst-golf-trip',
  '/blog/father-son-golf-trip',
  '/blog/40th-50th-birthday-golf-trip',
  '/blog/golf-trip-formats',
  '/blog/best-golf-destinations-october',
  '/blog/best-golf-destinations-march',
  '/blog/best-golf-destinations-november',
  '/blog/bandon-dunes-vs-scotland-golf-trip',
  '/blog/algarve-vs-ireland-golf-trip',
  '/blog/bandon-vs-pebble-vs-kiawah-golf-trip',
  '/blog/hidden-costs-golf-trip',
  '/blog/why-most-bachelor-golf-trips-suck',
  '/blog/couples-golf-trip-both-play',
  '/blog/first-ever-golf-trip',
  '/blog/golf-trip-flights-bag-fees',
] as const

function priorityFor(path: string): number {
  if (path === '/') return 1
  if (path === '/plan') return 0.9
  if (path === '/destinations') return 0.8
  if (path.startsWith('/destinations/')) return 0.8
  if (path === '/blog') return 0.6
  if (path.startsWith('/blog/')) return 0.7
  return 0.5
}

export default function sitemap(): MetadataRoute.Sitemap {
  return STATIC_PAGES.map((path) => {
    // Real per-page date from lib/content-dates.ts (generated by
    // scripts/generate-content-dates.mjs). Never `new Date()`: stamping every
    // URL with the build time makes all 65 lastmods identical and re-dates the
    // whole site on every deploy, which is why Google stopped trusting this
    // sitemap for crawl scheduling. A page whose content has not changed must
    // keep its old lastmod across deploys.
    const contentDate = CONTENT_DATES[path]

    return {
      url: path === '/' ? BASE_URL : `${BASE_URL}${path}`,
      // Omitted rather than faked when a route has no known date — <lastmod> is
      // optional, and an untrue one is worse than none.
      ...(contentDate ? { lastModified: contentDate } : {}),
      changeFrequency: path === '/' || path === '/plan' ? ('weekly' as const) : ('monthly' as const),
      priority: priorityFor(path),
    }
  })
}
